### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to MassiveCoreForgeFixes v1.0.0

### ISSUE THREAD

**Issue by FredericFernandes** [MarkehMe/MassiveCoreForgeFixes#3]
Hey when I'm launch my server I have this error :
 Could not pass event PlayerCommandPreprocessEvent to MassiveCoreForgeFixes v1.0.0

**Comment by markhughes** [comment]
This is not the full stack trace, please provide the entire error, your startup log, your factions and massivecore version, and your server version

**Comment by FredericFernandes** [comment]
I use Thermos-1.7.10 for Minecraft 1.7.10 and Factions 2.7.5 and MassiveCore 2.7.5.

----> http://pastebin.com/jYFN3qJ0

**Comment by markhughes** [comment]
`setSenderReferencesLater` method is different for 2.7.5, so I've added a fallback.

**Comment by markhughes** [comment]
### 🎉 MassiveCore Forge Fixes v1.2.0 solves this issue 🎉

```
Changelog
 * Added 1.7.5 support
```

You can download it from these locations:
- [GitHub](https://github.com/MarkehMe/MassiveCoreForgeFixes/releases/tag/v1.2.0)

---

This issue has now been closed. If there is still a problem, please [open a new issue](https://github.com/MarkehMe/MassiveCoreForgeFixes/issues/new).

**Comment by FredericFernandes** [comment]
Same error ....

--> http://pastebin.com/gRS2kCpx
