### ISSUE TITLE
Same error 

### ISSUE THREAD

**Issue by FredericFernandes** [MarkehMe/MassiveCoreForgeFixes#4]
http://pastebin.com/gRS2kCpx   With  MassiveCore Forge Fixes v1.2.0

**Comment by markhughes** [comment]
Left a reference over in the imports. Fixed in 6bee9625515693e013d2d606c7802272d89db2d8

**Comment by markhughes** [comment]
### 🎉 MassiveCore Forge Fixes v1.2.1 solves this issue 🎉

```
Changelog
 * Moved reference to database engine
```

You can download it from these locations:
- [GitHub](https://github.com/MarkehMe/MassiveCoreForgeFixes/releases/tag/v1.2.1)

---

This issue has now been closed. If there is still a problem, please [open a new issue](https://github.com/MarkehMe/MassiveCoreForgeFixes/issues/new).
