### ISSUE TITLE
Which Factions & MassiveCore Version

### ISSUE THREAD

**Issue by Slind14** [MarkehMe/MassiveCoreForgeFixes#6]
Hey,
which factions and massive core version is recommend to be used with this?

**Comment by markhughes** [comment]
Hi! 🍻 

This should work on 2.7+. I have not personally tested on the latest versions though.

2.8.10 should be fine! If you have any problems though just open up an issue and i'll do my best to fix it. I don't really make Bukkit plugins anymore - I'm quite invested in Sponge now.. but I'll still happy to maintain this. 😄

**Comment by Slind14** [comment]
Ahh I tried the two latest ones which didn't work. I'm currently using 2.8.6 as its the latest one that worked for me. I'll test 2.8.10 and attach the exception from the latest versions Thanks :)

**Comment by markhughes** [comment]
Thanks - let me know the stacktrace and I should be able to fix it by eye. 😃

**Comment by markhughes** [comment]
Closing for now. Let me know if it's still an issue - thanks
